### PR TITLE
Improve Code Picker Model UI

### PR DESCRIPTION
**Pull request by MSarmadQadeer**
I improved the UI of the code picker model. Also, I updated the docs accordingly.
You just need to update the gifs and screenshots.

Please check it out.

### CODE REVIEW

**Comment by fernan542** [comment]
Hello, thanks for your contributions.
I've seen that you've added a dependency for `circle_flag`. Have you tried just clipping the flag images to circle? This is to reduce some external dependencies in the package.

**Comment by MSarmadQadeer** [comment]
Hi! Thanks for the response.
All flag images are not of the same dimensions. also, I want to use good-quality scalable images. That is why I added that package.

**Comment by MSarmadQadeer** [comment]
This is what I achieved through customizing it in my project. All the previous settings are still available. I just added some new customizations for the user.

**Comment by fernan542** [comment]
I see. Previously I'm planning to add that feature in this package.
I think we should also allow user to choose if they want a circle or default(rectangular) flag for customization.

I'll update some part of your contributions because I'm planning to follow Material You too.
But more or less, your contribution is huge.

Thanks man! 🎉

P.S. I can't give a deadline LOL. Maybe this month, hopefully. :)

**Comment by AyushmanOfficial** [comment]
Hey @MSarmadQadeer, Can you provide me the source or just the parameter you used to tweak and made it look like that? i also want the flags ilke that 👍🏻

**Pull request merged**
